baseurl = "https://oscott.github.io/projects/"

title = "A Message:"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
publishDir = "docs"
[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Oliver Scott: A selection of projects"
  copyright = "&copy; Kunst Kernewek 999-019"
  sidebarAbout = [
    "<p>You have find me. </p><p>Mistake of your choice it is my pleasure. Whether searching up or stumbling in. Can we please make use of this embellishment in time? </p><p>I am forever grateful in enjoying your face at the reality of worldly achieved potential. at the same time, here is music and here is the art.</p><p>If you wont, then am i @oscott for your advisory?</p><p>Be excellent with each other well and in the same location of happy to your day.</p><p>// Multiverse (EU)</p>"
  ]
  # Contact page
  #    Since this template is static, the contact form uses www.formspree.io as a
  #    proxy. The form makes a POST request to their servers to send the actual
  #    email. Visitors can send up to a 1000 emails each month for free.
  #
  #    What you need to do for the setup?
  #
  #    - set your email address under 'email' below
  #    - upload the generated site to your server
  #    - send a dummy email yourself to confirm your account
  #    - click the confirm link in the email from www.formspree.io
  #    - you're done. Happy mailing!
  email = "os@koept.net"

  # # Nav links in the side bar
  # [[params.navlinks]]
  # name = "Home"
  # url = ""
  #
  # [[params.navlinks]]
  # name = "About"
  # url = "about/"
  #
  # [[params.navlinks]]
  # name = "Get in touch"
  # url = "contact/"
  #
   [params.social]
  # googleplus    = "full profile url in googleplus"
  # email         = "os@koept.net"
  # twitter       = "full profile url in twitter"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "https://www.instagram.com/koe.pt"
  # github        = "https://github.com/oscott/projects"
